name: Deployment Setup

on: push

jobs: 
  deploy: 
    runs-on: ubuntu-latest

    steps: 
      - name: print single line
        run: echo ${{secrets.THEME_ID}}

      - name: Check secrets
        run: | 
          if [ "${{secrets.THEME_ID}}" == "188771827987" ]; then
            echo "Theme ID Matched"
          else
            echo "not Exists"  
          fi 
