name: Shopify Theme Pipeline

on: 
  push: 
    branches-ignore:
      - main
env: 
  SHOPIFY_FLAG_STORE: ${{ secrets.SHOPIFY_STORE }}
  SHOPIFY_CLI_THEME_TOKEN: ${{ secrets.SHOPIFY_ADMIN_TOKEN }}
  THEME_NAME: ${{ github.ref_name }}

jobs:  
  Optimized:
    runs-on: ubuntu-latest
    steps: 
      - name: Check JavaScript size
        run: |
          LIMIT=500000   # 500 KB

          find assets -name "*.js" | while read file; do
            SIZE=$(wc -c < "$file")

            if [ "$SIZE" -gt "$LIMIT" ]; then
              echo "$file exceeds 500 KB"
              exit 1
            fi
      
  Performance: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with: 
          node-version: 24

      - name: npm install
        run: npm ci

      - name: Lighthouse Run
        run: npx lhci autorun      

