name: Delete Preview Theme

on: delete

env: 
  SHOPIFY_FLAG_STORE: ${{ secrets.SHOPIFY_STORE }}
  SHOPIFY_CLI_THEME_TOKEN: ${{ secrets.SHOPIFY_ADMIN_TOKEN }}
  THEME_NAME: ${{ github.event.ref }}

jobs: 
  theme_delete:
    runs-on: ubuntu-latest
    steps: 
        - name: Checkout repository
          uses: actions/checkout@v4
          with: 
            ref: main

        - name: Install Shopify CLI
          run: npm install -g @shopify/cli @shopify/theme

        - name: Delete Theme  
          id: find_theme
          run: |
            THEME_ID=$(shopify theme list --json \
              | jq -r --arg NAME "$THEME_NAME" '.[] | select(.name==$NAME) | .id' \
            )

            if [ -z "$THEME_ID" ] || [ "$THEME_ID" = "null" ]; then
              echo "Theme not found"
            else
              echo "Theme found: $THEME_ID"
              echo "theme_id=$THEME_ID" >> "$GITHUB_OUTPUT"
              shopify theme delete --theme $THEME_ID --force
            fi

            echo "Found theme id: $THEME_ID"
            echo "theme_id=$THEME_ID" >> "$GITHUB_OUTPUT"  

